JuliaDiff/ChainRulesCore.jl

LICENSE.md, Project.toml, README.md, docs/Project.toml, docs/make.jl, docs/src/api.md, docs/src/index.md, src/ChainRulesCore.jl, src/differentials.jl, src/rules.jl, test/rules.jl, test/runtests.jl, test/test_util.jl
After offline discussion with @oxinabox :)
=> Name package `ChainRulesCore.jl`

.travis.yml, Project.toml
This test will sometimes fail for breaking changes,
but that is Ok,
we can notice it and then we can explain why in a comment in a PR
(and link to downstream fix PR)
=> Test that works with ChainRules

src/differentials.jl, src/rule_definition_tools.jl, src/rules.jl, test/rules.jl, test/runtests.jl
Another attempt... This should be correct now. @oxinabox?
=> fix wirtinger mechanism

src/differentials.jl, test/differentials.jl
Some minor code clean up I noticed when reading through files
=> Change to more appropraite error types

src/rules.jl
This is some early discussion on #68 
I have transferred it to the comments in #68
=> Remove old notes on rules for higher order functions

src/differential_arithmetic.jl, src/differentials/does_not_exist.jl, test/differentials/does_not_exist.jl, test/runtests.jl
Result of discussion @willtebbutt  and I had.
Also matches a older discussion had with @MikeInnes
and some ideas taken from Swift.
crossref #71 and #52
=> Make DoesNotExist more clearly like Zero

Project.toml, src/differentials/composite.jl, src/differentials/one.jl, src/differentials/zero.jl, src/rule_definition_tools.jl, src/rules.jl, test/rules.jl
Fix https://github.com/JuliaDiff/ChainRulesCore.jl/issues/74
=> Fuse `frule` and pushforward

Project.toml, src/differential_arithmetic.jl, test/differentials/zero.jl
We need this for better performance.
=> `muladd` with `Zero()`

src/differentials/abstract_differential.jl
This is stuff that has been discussed several times but not put into docstrings yet.
It should be expanded in https://github.com/JuliaDiff/ChainRules.jl/pull/133
but this is the shorter docstring version.
=> Document extern and AbstractDifferential

src/differentials/composite.jl, test/differentials/composite.jl
=> Make getproperty on unset Composite properties return Zero(). 

src/differentials/abstract_zero.jl, test/differentials/abstract_zero.jl
- useful for https://github.com/JuliaDiff/ChainRules.jl/pull/157
- xref https://github.com/JuliaDiff/ChainRulesCore.jl/issues/37
=> Add some linear operators for Zero

src/ChainRulesCore.jl, src/differentials/composite.jl, test/differentials/composite.jl
=> Add canonicalize for Composites

Project.toml, src/ChainRulesCore.jl
=> Export AbstractZero

docs/src/index.md
- needed to be indented to actually go in the box
- before:
=> Fix syntax for admonition

.travis.yml, docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/api.md, docs/src/index.md, src/differentials/abstract_differential.jl, src/differentials/thunks.jl, src/rules.jl
- should appear at http://www.juliadiff.org/ChainRulesCore.jl/preview-PR131
- Changes to docs are 
- home page example: http://www.juliadiff.org/ChainRulesCore.jl/preview-PR131/#Example-of-using-ChainRules-directly.-1
- organisation of API docs: http://www.juliadiff.org/ChainRulesCore.jl/preview-PR131/api.html
=> Fix doctests; Organise and improve some docs

docs/src/FAQ.md, docs/src/writing_good_rules.md
- preview should appear at http://www.juliadiff.org/ChainRulesCore.jl/preview-PR125/
=> Add ChainRulesTestUtils to FAQ

docs/Manifest.toml, docs/src/FAQ.md
- I missed this mistake in #125
=> Fix docs page xref

docs/make.jl, docs/src/design/many_differentials.md
I was asked this on slack, so I wrote it out in full.
I think we probably should have a folder in the docs full of these design decisions.
This probably needs a lot of editting.
=> Document why we have a many-many relationship between differential types and primal types

Project.toml, src/differentials/composite.jl, test/differentials/composite.jl
As discussed on Slack, I think this makes sense to have.
=> define keys(::Composite)

Project.toml, src/differential_arithmetic.jl, test/differentials/abstract_zero.jl, test/differentials/one.jl
Needed for https://github.com/JuliaDiff/ChainRules.jl/pull/196/files
=> Add real and imag methods for One and Zero

Project.toml, src/differentials/composite.jl, test/differentials/composite.jl
Fixed issue noticed by @willtebbutt  in 
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/43
=> Workout types of Composite sum correctectly

docs/src/FAQ.md
Sometimes people ask me this.
This is the best I have
=> Add a section on learning resources

docs/src/writing_good_rules.md
=> Remove reference to pushforward in writing good rules

docs/src/writing_good_rules.md
I think cna just remove this without replacement since we now do give the adjoint for complex
=> One can now use adjoint freely

src/differentials/abstract_zero.jl
As a non-native speaker, I had some trouble understanding the documentation in this file. This is an attempt to make it easier to read.
There is a bit that I still don't understand: I'll add a comment directly on those lines.
=> spelling and grammar

docs/src/autodiff/operator_overloading.md
@MasonProtter  pointed this out
=> Remove redundant where from operator overloading docs

docs/src/autodiff/operator_overloading.md
@MasonProtter  pointed this out.
=> Correct argument order for on_new_rule in docs

Project.toml, src/differentials/composite.jl, test/differentials/composite.jl
=> add reverse method for Composite

Project.toml, src/differentials/composite.jl, test/differentials/composite.jl
=> fix equality of Composites

.github/workflows/IntegrationTestChainRules.yml
=> Do more reverse dependency tests

docs/Manifest.toml, docs/Project.toml, docs/src/writing_good_rules.md
It was quite educational to go through the cases by writing the example functions as well. I can remove them however if people think it is too much detail.
=> add "when to write rules" advice

docs/src/FAQ.md
It just summarizes so many things.
There are no excellent books, but at least we have github issues with excessively long comments.
google-research/dex-lang#454
cc @dan-zheng
=> Add recommended reading: Dan Zheng's DexLang issue comment

docs/make.jl, docs/src/assets/chainrules.scss, docs/src/design/changing_the_primal.md
I have been meeting to write this for ages.
Its going to be like the other one in the design notes where it blurs the idea between documentation and a blog post.
Rendered preview
https://www.juliadiff.org/ChainRulesCore.jl/previews/PR282/design/changing_the_primal.html
=> "Changing the Primal" Design Notes

docs/src/gradient_accumulation.md
another missing docs block (similar to #294)
=> Add another missing code-block syntax to fix rendering

test/rule_definition_tools.jl
adapt to https://github.com/JuliaLang/julia/pull/38379
=> fix tests on Julia nightly

docs/src/FAQ.md
As per discussion on slack with @oxinabox
=> Add note on thunks

docs/src/opting_out_of_rules.md
@sethaxen  corrected my misconception of skew-symmetric matrixes.
Example still holds
=> Fix skew-symmetric comment

docs/src/FAQ.md, docs/src/design/changing_the_primal.md
When i wrote changing the primal i forgot there was a mini-version of it in the FAQ
=> Crosslink FAQ to Changing the Primal

Project.toml, src/projection.jl, test/projection.jl
Closes one case of  #410, closes #423. Are there tidier ways?
=> Fix two bugs in `ProjectTo`

docs/src/writing_good_rules.md
This is about working around https://github.com/JuliaLang/julia/issues/40990
=> Document about being careful about pullbacks that call themselves

docs/src/writing_good_rules.md
cross references: https://github.com/JuliaLang/julia/issues/38241
=> Mention that sometimes you should infact use 0 rather than zerotangent

docs/src/design/changing_the_primal.md
=> Clarify docs referenced PullbackMemory as a Fixed Thing

Project.toml, src/tangent_types/thunks.jl, test/tangent_types/thunks.jl
Closes #472 
much less complex than https://github.com/JuliaDiff/ChainRulesCore.jl/pull/473
=> Remove piracy of diagm

docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/videos.md
Closes #434 
Requires https://github.com/JuliaDiff/DocThemeIndigo.jl/pull/3
so it renders the videos at full-size.
With that done it should look like the following screen shot.
=> Link to videos

docs/make.jl, docs/src/index.md, docs/src/rule_author/example.md, docs/src/rule_author/intro.md, docs/src/rule_author/writing_good_rules.md
Closes #116 , closes #379 , closes #508
=> Add a pedagogical example

.github/workflows/IntegrationTest.yml
Recommended by @mcabbott  in https://github.com/JuliaDiff/ChainRulesCore.jl/pull/524#issuecomment-1000597727
=> Reverse dependency test ChainRulesTestUtils

Project.toml, src/tangent_types/thunks.jl, test/tangent_types/thunks.jl
Fix JuliaDiff/ChainRulesTestUtils.jl#233 (replaces https://github.com/JuliaDiff/ChainRules.jl/pull/572)
=> fix `iterate(@thunk ())`

Project.toml, src/projection.jl, test/projection.jl
=> fix projecting `Tangent{Complex}` to `Number`

docs/src/rule_author/superpowers/ruleconfig.md
This PR corrects 2 small typos in the documentation on `RuleConfig`
=> 2 small typos in ruleconfig.md

Project.toml, src/tangent_types/thunks.jl
=> Fix broken link in the docstring of `Thunk`

docs/src/rule_author/tangents.md
This is a bunch of things we say all the time but haven't ever documented
Closes #500
=> Improve documentation of tangent types

docs/src/rule_author/example.md
This resolves #593. I also added an example of testing the `rrule` with `ChainRulesTestUtils` and fixed a small typo.
=> [Docs] Fix pedagogical example

docs/src/index.md
Solves https://github.com/JuliaDiff/ForwardDiff.jl/issues/579
=> Add link to ForwardDiffChainRules.jl

docs/src/FAQ.md
=> Minor formating fix

src/tangent_arithmetic.jl, test/tangent_types/structural_tangent.jl
Closes https://github.com/JuliaDiff/ChainRulesCore.jl/issues/641
=> Implement Tangent subtraction

docs/src/index.md
The tools didn't have newlines between them making it hard to read
=> Update line spacing in index.md
