- src/differentials.jl
- src/rule_definition_tools.jl
- src/rules.jl
- test/rules.jl
- test/runtests.jl
This PR Reverts #13 as it broken ChainRules.
@simeonschaub 
I know why it does so, because it changes how we decide how many paritals there are.
Full details  see https://github.com/JuliaDiff/ChainRulesCore.jl/pull/13#discussion_r318047418
```
julia> ares = frule(sincos, 1)
((0.8414709848078965, 0.5403023058681398), (Rule{getfield(ChainRules, Symbol("##627#634")){Float64},Nothing}(getfield(ChainRules, Symbol("##627#634")
){Float64}(0.5403023058681398), nothing), Rule{getfield(ChainRules, Symbol("##629#636")){Float64},Nothing}(getfield(ChainRules, Symbol("##629#636")){
Float64}(0.8414709848078965), nothing)))
```
```
julia> ares = frule(sincos, 1)
((0.8414709848078965, 0.5403023058681398), Rule{getfield(ChainRules, Symbol("##627#632")){Float64},Nothing}(getfield(ChainRules, …
```
> Revert #13

- src/rule_types.jl
- test/rule_types.jl
I have some ideas about improving it more,
but this at least avoids showing unneeded type-params.
So it is a bit simpler to read.
But still can be recreated from input.
> Improve display of rules

- Project.toml
- src/ChainRulesCore.jl
- src/differential_arithmetic.jl
- src/differentials.jl
- src/rule_definition_tools.jl
- src/rule_types.jl
- test/differentials.jl
- test/rule_types.jl
- test/rules.jl
- test/runtests.jl
Closes #16 
I have not yet checked if it works with ChainRules.jl
probably a few minor tweaks needed
A follow up PR might remove the 1 arg form of `Rule`.
And just allow functions to be used in its place
> Remove all uses of Cassette and define the arithmetic directly

- Project.toml
- src/differentials.jl
- test/differentials.jl
and improve `show(::Thunk)`
and make Thunk callable
This closes #47 
Show was dispalcing redundant type-params so I also cleaned that up,
> make extern(::Thunk) recursive

- src/rule_types.jl
- src/rules.jl
ChainRulesCore doesn't define any rules,
so we can't have doctests that rely on them.
> no doctests

- Project.toml
- src/ChainRulesCore.jl
- src/differential_arithmetic.jl
- src/differentials.jl
- src/operations.jl
- test/runtests.jl
closes #10 
@willtebbutt and I sat down and did this
> Remove Casted

- src/differentials.jl
- test/differentials.jl
Is this enough to close #57 ?
Should I test this? Maybe can throw error, then access the backtrack as a string,
and then make sure the right file name occurs?
```
julia> demo_pb() = @thunk(error("no"))
demo_pb (generic function with 1 method)
julia> extern(demo_pb())
ERROR: no
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] (::var"#15#16")() at /Users/oxinabox/JuliaEnvs/ChainRulesWorld/ChainRulesCore.jl/src/differentials.jl:216
[3] (::Thunk{var"#15#16"})() at /Users/oxinabox/JuliaEnvs/ChainRulesWorld/ChainRulesCore.jl/src/differentials.jl:223
[4] extern(::Thunk{var"#15#16"}) at /Users/oxinabox/JuliaEnvs/ChainRulesWorld/ChainRulesCore.jl/src/differentials.jl:224
[5] top-level scope at REPL[12]:1
```
```
julia> extern(demo_pb())
ERROR: no
Stacktrace:
[1] error(::String) at …
```
> Record where thunks actually created

- src/ChainRulesCore.jl
- src/differential_arithmetic.jl
- src/differentials.jl
- test/differentials.jl
- test/runtests.jl
- closes #17 
- ~is breaking~ not breaking if using `deprecate_binding`
> Rename `DNE` -> `DoesNotExist`

- .cirrus.yml
- .travis.yml
As shown above (and below) now they will be shown seperately
The FreeBSD ones are for ChainRules.jl integration tests.
The TravisCI ones are for the ChainRulesCore.jl unit tests
It was getting annoying not being able to see from a PR if it was just integration tests failing.
(Which could be expected)
Or if it was also unit tests
This close #49
> move integration tests over to CirrusCI

- Project.toml
- src/ChainRulesCore.jl
- src/differential_arithmetic.jl
- src/differentials.jl
- test/differentials.jl
This swaps `extern` for `unthunk`
which just removes a layer of thunking,
rather than attempting to fully get from a differential to a primal
It is needed for #61  but is distrinct (that PR currently sits ontop of this one though)
Note that even in double thunking cases:
`1+@thunk(@thunk(2))` becomes `1 + @thunk(2)` becomes `1+2`
so addition is still fine.
This also occurs in #54
> add Unthunk

- src/ChainRulesCore.jl
- src/compat.jl
- src/composite_core.jl
- src/differential_arithmetic.jl
- src/differentials.jl
- src/differentials/abstract_differential.jl
- src/differentials/composite.jl
- src/differentials/does_not_exist.jl
- src/differentials/one.jl
- src/differentials/thunks.jl
- src/differentials/wirtinger.jl
- src/differentials/zero.jl
- test/differentials.jl
- test/differentials/composite.jl
- test/differentials/one.jl
- test/differentials/thunks.jl
- test/differentials/wirtinger.jl
- test/differentials/zero.jl
- test/differentials_common.jl
- test/runtests.jl
This will finally finish resolving #8 
I think before it is done it needs `unthunk` to be used instead of `extern` #56
> Introduce Composite for structured deriviatives

- src/compat.jl
- src/differentials/composite.jl
Partially undoes #81 
in light of https://github.com/JuliaLang/julia/issues/34283
Turns out putting code outside the `if @generated` causes it to always run at runtime
> Bring back nongenerated backing

- src/rule_definition_tools.jl
This replaces #76 
just because it was annoying to rebase.
Motivation remains:
> It was pointless.
> 
> Either:
> 
>     There was 1 derivative being propagated, in which case there should not have been any thunking (see docs added in #75)
>     Or there was multiple, in which case they all get unthunked when the + happens.
>
> remove scalar thunking (attempt 2)

- src/differentials/composite.jl
- test/differentials/composite.jl
> use Zero rather than DoesNotExist for NO_FIELDS

- Project.toml
- src/differential_arithmetic.jl
- src/differentials/zero.jl
- src/rule_definition_tools.jl
- test/differentials/zero.jl
- test/rules.jl
Master behavior
```julia
julia> @scalar_rule(one(x), Zero())
julia> frule(one, 1, Zero(), [1, 2])
(1, Zero())
julia> frule(one, 1, Zero(), One())
(1, Zero())
```
Desirable behavior
```julia
julia> @scalar_rule(one(x), Zero())
julia> frule(one, 1, Zero(), [1, 2])
(1, [0, 0])
julia> frule(one, 1, Zero(), One())
(1, Thunk(var"#8#10"())
)
```
> Eagerly evaluate ::Zero * ::Any

- Project.toml
- src/rule_definition_tools.jl
I also added `@muladd` to optimize `propagation_expr`. It rewrites `a*b + c*d` to `muladd(a, b, c*d)`.
> Broadcast the `propagation_expr` for vector mode AD

- Project.toml
- src/differentials/does_not_exist.jl
- src/differentials/one.jl
- src/differentials/zero.jl
- test/rules.jl
It also saves computation since
```julia
goo(x) = (One.() .* x) .+ (One.() .* x)
```
is now the same as
```julia
goo(x) = (One() .* x) .+ (One() .* x)
```
.
> Make `One`, `Zero`, and `DNE` inferable when broadcasting with StaticArrays

- Project.toml
- src/differentials/thunks.jl
- test/differentials/thunks.jl
Previously it `extern`ed.
I didn't know it did that either, so was surprised tests passed.
This is part of #94
> Make thunked unthunk before broadcasting

- src/operations.jl
- src/rule_definition_tools.jl
just noticed when reading through the code
> Tidy some docs

- README.md
- test/rules.jl
- test/runtests.jl
- YAS and Blue are compatible enough styles there didn't need to be changed
- I removed unneed imports and reduced a comment that went over the line length 😆 
- This just commits us to the Blue Style in general (kinda partner to https://github.com/JuliaDiff/ChainRules.jl/pull/165)
> Adopt Blue Style

- .travis.yml
- Project.toml
- docs/src/index.md
- src/rule_definition_tools.jl
- src/rules.jl
- test/rules.jl
Implements option 2 from #128 . Adds API regression tests to ensure that the considerations made there don't slip through the cracks in any future API revisions.
Currently got a weird type instability thing @oxinabox any thoughts?
> Sort out frule API

- .travis.yml
At some point we can look into changing this, I think it is to `@allocated` changing 
(and we now have `BenchmarkTools.@ballocated`)
but first we should let 1.4 get released
> Allow failures on 1.4

- Project.toml
- src/ChainRulesCore.jl
- useful for https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/20/files#diff-234b922abbcf04ec39f433cf6ce21772R17 where adding a method for `AbstractThunk` makes more sense (to me) than `AbstractDifferential`
> Export AbstractThunk

- Project.toml
- docs/make.jl
- docs/src/api.md
- docs/src/debug_mode.md
- src/ChainRulesCore.jl
- src/debug_mode.jl
- src/differential_arithmetic.jl
- test/differentials/composite.jl
closes #82 
Gives us full performance for addition of primal and differential,
at the cost of the good error message.
But by enabling the `ChainRulesCore.debug_mode() = true`
the good error message comes back.
```julia
julia> using ChainRulesCore, BenchmarkTools
julia> struct Foo
x::Float64
end
julia> foo = Foo(0.5)
Foo(0.5)
julia> Δfoo = Composite{typeof(foo)}(; x=0.4)
Composite{Foo}(x = 0.4,)
julia> @benchmark $foo + $Δfoo  # good performance
BenchmarkTools.Trial: 
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     1.247 ns (0.00% GC)
median time:      1.465 ns (0.00% GC)
mean time:        1.439 ns (0.00% GC)
maximum time:     15.312 ns (0.00% GC)
--------------
samples:          10000
evals/sample:     1000
julia> ChainRulesCore.debug_mode() = true
julia> …
```
> Add Debug Mode

- .travis.yml
- Project.toml
- test/differentials/composite.jl
- test/runtests.jl
Resolves #141 . Includes:
- replacing `@allocated` with `BenchmarkTools.@ballocated`
- requiring CI to pass on 1.4, to ensure that this is actually tested
- bump patch version
> [WIP] Fix allocations on 1.4

- docs/src/index.md
This takes @aisopous's PR from December that I never got round to merging,
and shifts it over here to where the docs are.
https://github.com/JuliaDiff/ChainRules.jl/pull/135
I think @aisopous addressed all comments there, explaining why the points were correct.
It also deletes the heavier math section which has issues. 
Since this section covers our need for rigerous math better than that section ever could.
This thus closes #139  
A follow up PR to breakup this page in the docs is needed.
---
Preview of Docs:
http://www.juliadiff.org/ChainRulesCore.jl/preview-PR147/#Geometric-interpretation-of-reverse-and-forwards-mode-AD-1
> Replace Heavier Math section with Geometeric section

- docs/src/design/many_differentials.md
- following https://github.com/JuliaLang/julia/pull/35554
which agrees with the point made here, but shows the
given code to be misleading.
- i don't know if this is the best replacement text... maybe just delete that clause (since it is enough that  `DateTime`s cannot be added to each other
> Remove misleading `zero(::DateTime)` example

- Project.toml
- docs/src/index.md
- src/rule_definition_tools.jl
- test/rules.jl
(update @scalar_rule) 
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/152
interestingly there are no tests that needed to be updated for this, which seems bad.
Might want some tests added before merging.
Though I have now cross tested against everything downstream of this
> Make all pullbacks only take a single input

- test/differentials/composite.jl
- Should fix the issue seen here https://github.com/JuliaCI/NanosoldierReports/blob/18bb6d85b20e25f1a9f2f312963f4b8b4fe7082e/pkgeval/by_hash/a340bf1_vs_3c50b7f/logs/ChainRulesCore/1.5.0-DEV-fc8aa8666a.log
- I've no idea which change(s) in Base fixed this 🤷 
- There's no binary for v1.5 as far as i know, but i tested on nightly and it passed (Version 1.6.0-DEV.108 (2020-05-26) Commit 3995a02e14)
> Test `construct` allocations on Julia v1.5+

- docs/src/FAQ.md
Adds a rigorous definition of how `frule` and `rrule` are to be implemented for complex functions.
> Define chain rules for complex functions

- Project.toml
- src/rule_definition_tools.jl
- test/rules.jl
- test/runtests.jl
Following https://github.com/JuliaDiff/ChainRules.jl/issues/210, #167, this PR conjugates the partial derivatives in the `rrule` defined by `@scalar_rule` and documents that the the macro should only be used for holomorphic functions.
> Conjugate partials in scalar rrule 

- docs/src/index.md
we say `pullback` not `rule` and the word `accumulate` has a particular meeting so lets not use that
> clarify comment about reverse mode by hand

- Project.toml
- src/differentials/composite.jl
- test/differentials/composite.jl
Fix for issue [177](https://github.com/JuliaDiff/ChainRulesCore.jl/issues/177).  Case to explicitly deal with Composite being given zero arguments.
> Differential addition for empty tuples fix in composite.jl

- docs/src/index.md
- comment in more multiplication
- remove unthunking as it isn't required for scalar rules
> simplify example of calling AD by hand

- Project.toml
- src/differential_arithmetic.jl
- test/differentials/abstract_zero.jl
- test/differentials/one.jl
Sometimes you want to use `complex(a, b)` instead of `a + im * b` in a rule, but it doesn't work if `a` or `b` end up being `Zero` or `One`. This adds the corresponding overloads for `Zero`, `One`, and mixtures of the two.
> Add overloads of complex for One and Zero

- docs/src/arrays.md
Changes:
- two spaces between code and end of line comments
- info instead of note on one box so CSS colors it right
- `==` in comments saying that the line is another way of writing a thing
- `==logabsdet(A)` for `logabsdet(F)`
> Small tweaks to docs on deriving rules

- docs/src/index.md
Trailing full-stops sometimes means attempts to link
directly to these section don't work 
(because the `.` gets excluded from the link, but is
needed for the link to work).
> Remove trailing `.` from headings

- Project.toml
- src/ChainRulesCore.jl
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
- test/runtests.jl
Closes #150 
This relies on `DoesNotExist()` iterating to give itself, since we don't knopw how many returns a forward mode rule needs.
Which i thought it did, but maybe we removed that at one point?
Its also useful for use with Composites.
> nondifferentiable macro

- Project.toml
- src/ruleset_loading.jl
It was annoying trying to find errors in hook functions
before this PR an error might be:
```julia
┌ Error: Error triggering hook
│   hook_fun = generate_overload (generic function with 1 method)
│   sig = Tuple{typeof(hypot),T,T} where T<:Union{Real, Complex}
│   exception =
│    TypeError: in <:, expected Type, got a value of type TypeVar
└ @ ChainRulesCore ~/JuliaEnvs/ChainRulesWorld/ChainRulesCore.jl/src/ruleset_loading.jl:139
```
but after this PR it is
```julia
┌ Error: Error triggering hook
│   hook_fun = generate_overload (generic function with 1 method)
│   sig = Tuple{typeof(hypot),T,T} where T<:Union{Real, Complex}
│   exception =
│    TypeError: in <:, expected Type, got a value of type TypeVar
│    Stacktrace:
│     [1] #66 at ./none:0 [inlined]
│     [2] iterate at …
```
> include backtrace in error message from on_new_rule hook failure

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
Follow up to #207 
fixes #216 
Following this we just always accept kw-args and then just allways pass them on
> Add kwarg support to at-nondifferentiable

- Project.toml
- docs/Manifest.toml
- docs/src/api.md
- src/ChainRulesCore.jl
- src/accumulation.jl
- test/accumulation.jl
- test/rules.jl
- test/runtests.jl
This closes #113 
at least the most important part.
I don't think we need `store!`,
and it doesn't do multi-arg accumulation, on the basis that we can add that later, lets not gold-plate this with features we don't yet need.
We can open a follow up issue about that after this is merged
It is named `accumulate!!` after the [BangBang.jl](https://github.com/JuliaFolds/BangBang.jl) convention.
a suffix of `!!` means I might mute the input, or i might not, but i will return definately return the thing
> Introduce add!!

- Project.toml
- src/rule_definition_tools.jl
- src/rules.jl
- test/rule_definition_tools.jl
- test/rules.jl
Fix #211
I am marking this as a patch, because I think #211 was a bug.
And this shoul;dn't break anyway as `Composite{Tuple}` acts just like a tuple for most purposes
> Make scalar_rule's frule return a Composite not a tuple

- Project.toml
- test/rules.jl
- test/runtests.jl
Removes the tests that depend on FiniteDifferences so it can be dropped, addressing #227.
> Remove FiniteDifferences from tests

- Project.toml
- src/differentials/composite.jl
- test/differentials/composite.jl
> Make `getproperty` on `Composite` unthunk

- src/differentials/thunks.jl
@nickrobinson251  pointed out:
> (not this PR, afaiu): InplaceableThunk prints kinda funny (split over two lines)
> 
>     julia> ithunk
>     InplaceableThunk(Thunk(var"#15#17"())
>     , var"#16#18"())
Because `repr(::Thunk)` hcalls `show(::Thunk)` which calls `println` 
so we need to strip it out before using it in the `show` for `InplaceThunk`.
idk if this is the right fix, or if the problem is that `show(::Thunk)` should just use `print` not `println` ?
> Fix show on InplaceableThunks

- Project.toml
- docs/Manifest.toml
- docs/src/api.md
- docs/src/debug_mode.md
- src/ChainRulesCore.jl
- src/accumulation.jl
- test/accumulation.jl
- test/runtests.jl
> Make add!! decide if mutable or not

- Project.toml
- src/differentials/composite.jl
- test/differentials/composite.jl
Just discovered we were missing these, can't think of any reason not to define them.
> define haskey/hasproperty on Composite

- src/rule_definition_tools.jl
- test/demos/forwarddiffzero.jl
- test/demos/reversediffzero.jl
- test/rule_definition_tools.jl
> support constructors with non_differentiable

- Project.toml
- src/differentials/abstract_zero.jl
- test/differentials/abstract_zero.jl
Helps with https://github.com/JuliaDiff/ChainRulesCore.jl/pull/112
> Add convert for AbstractZero

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
- test/runtests.jl
> Support Vararg in @non_differentiable macro

- Project.toml
- src/rule_definition_tools.jl
I recall this was causing problems for @dpsanders  a while ago.
I am not sure if it still is, but it seems reasonable to do this.
> Make sure pullbacks from scalar_rule's inline

- Project.toml
- docs/Manifest.toml
- src/ChainRulesCore.jl
- src/rule_definition_tools.jl
This PR removes the dependency on the MuladdMacro package and instead explicitly adds `muladd` calls to the constructed expression.
The propagation expression is so "clean" with clearly define multiplications and additions that the `muladd` calls can easily be added manually instead of applying the `@muladd` macro that takes care of many special cases such as subtraction etc.
There is one catch to it: it seems currently the `@muladd` macro is applied to the full expression including the partials and therefore also rewrites the user-provided definitions whereas this manual construction only adds `muladd` calls to the products and sum of partials and input gradients.
> Replace MuladdMacro with manual application of `muladd`

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
Turns out that we were not escaping the inputs correctly in the pullbacks generated by `@scalar` rule.
And in the case of multi-input functions that actually ended up creating and assigining to a global variable during the input destructuring.
Which must be some edge case of the compiler, as normally it errors if you try to do that.
```julia
julia> module FooMod
bar((FooMod.x, FooMod.y)) = 1
@eval FooMod  bar((1,2))
end
ERROR: cannot assign variables in other modules
Stacktrace:
[1] setproperty! at ./Base.jl:27 [inlined]
[2] bar(::Tuple{Int64,Int64}) at ./REPL[11]:2
[3] top-level scope at none:1
[4] eval(::Module, ::Any) at ./boot.jl:331
[5] top-level scope at REPL[11]:3
```
Anyway that in turn was making the `sincos` 's rule in ChainRules.jl type-unstable because it was accessing this …
> make creation of inputs to propagation consistently hyginic

- test/differentials/composite.jl
For some reason Julia 1.0.5 allocates less on linux than on Mac or Windows.
Which has been making the test that is marked s `@test_broken` actually pass.
Which triggers an Error and makes CI fail.
E.g.
https://github.com/JuliaDiff/ChainRulesCore.jl/pull/272/checks?check_run_id=1688697214
I don't think we care to mark it broken.
We are not going to fix allocations on 1.0 anyway.
And we have tests lower down in that section that do make claims about 1.0 allocations.
> Stop at-test_broken allocations on 1.0, and just don't test it

- docs/src/writing_good_rules.md
Added a few lines to the docs recommending the usage of rule definition tools
> recommend using rule definition tools in docs

- Project.toml
- src/ChainRulesCore.jl
- src/differentials/composite.jl
- test/differentials/composite.jl
This PR resolves two issues that make unpacking a `Composite` uninferrable. On Julia 1.5, currently the following operations are uninferrable:
```julia
function foo(x)
a, b = x
return (a, b)
end
struct Bar
a
b
end
bar(x) = (x.a, x.b)
julia> using LinearAlgebra, ChainRulesCore, Test
julia> x = (3.0, 4); ∂x = Composite{typeof(x)}(5.0, 6);
julia> @inferred foo(∂x)
ERROR: return type Tuple{Float64,Int64} does not match inferred return type Tuple{Union{Float64, Int64},Union{Float64, Int64}}
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] top-level scope at REPL[9]:1
julia> y = Bar(3.0, 4); ∂y = Composite{typeof(y)}(a=5.0, b=6);
julia> @inferred bar(∂y)
ERROR: return type Tuple{Float64,Int64} does not match inferred return type Tuple{Float64,Union{Zero, Int64}}
Stacktrace:
[1] …
```
> Make unpacking a Tuple or NamedTuple Composite type-inferrable

- docs/src/writing_good_rules.md
pullback takes in the derivative w.r.t. the function output (not input), and this makes the variable name follow that
> fix confusing variable name

- .github/workflows/CI.yml
- .github/workflows/JuliaNightly.yml
There was a CI Cache bug affecting the previous ci files (found in a different project). This should fix that, and this moves the 1.3 test to a 1.5 test.
> Fix CI cache, use 1.5 instead of 1.3 test

- .github/workflows/CI.yml
- docs/Manifest.toml
- docs/make.jl
- docs/src/gradient_accumulation.md
This gives some more instructional documentation about `InplaceableThunk` and `add!!`.
It's been on my todo to give more documentation on this.
@dan-zheng was asking on twitter so I wrote it up.
Preview  docs here:
https://www.juliadiff.org/ChainRulesCore.jl/previews/PR287/gradient_accumulation.html
> Document about Gradient Accumulation

- docs/src/gradient_accumulation.md
Noticed this docs page wasn't rendering correctly due to missing triple-backticks
> Add missing code-block syntax to fix rendering

- Project.toml
- test/demos/forwarddiffzero.jl
- test/demos/reversediffzero.jl
This was broken by https://github.com/JuliaLang/julia/pull/38136
> fix AD demos on Julia nightly

- .github/workflows/CI.yml
- .github/workflows/JuliaNightly.yml
Ref https://github.com/JuliaDiff/ChainRulesCore.jl/pull/301#issuecomment-776671763
> make Julia nightly CI a separate workflow

- .github/workflows/JuliaNightly.yml
i missed this in #302 -- the comment about "nightly scheduled" is no longer true :)
> Update comment in JuliaNightly workflow

- README.md
- noticed these were out of date when reviewing #302
> Update badges to show build status and coverage now we use GithubActions

- docs/src/writing_good_rules.md
I enjoyed reading this clear doc page! In the end fixed an rrule typo I think, timings and results on the example are left unchanged :+1:
> Fix rrule of sum3 example

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
solves #317, replaces #318. Same change to src but with tests
@devmotion  do you want to review?
> Add qualification to at-nondifferentiable

- src/rule_definition_tools.jl
Before:
```
julia> @which rrule(typeof, 1.0)
rrule(::typeof(typeof), var"269"; kwargs...) in ChainRules at [...]/rule_definition_tools.jl:352
```
After:
```
julia> @which rrule(typeof, 1.0)
rrule(::typeof(typeof), var"269"; typeof_pullback) in ChainRules at [...]/src/rulesets/Core/core.jl:8
```
N.B.:, currently includes the commit from #308, because it touches the same code, but should be automatically rebased once that is in.
> Change LineNumber nodes to point at definition site 

- .github/workflows/IntegrationTest.yml
ChainRules.jl is failing tests in 1.6 because of type inference.
til we get around to fixing that seems best to keep our integration tests running on 1.5
> Pin reverse dependency tests to 1.5

- Project.toml
- src/rule_definition_tools.jl
This PR replaces `strip_linenos` (the function, not the macro) with `Base.remove_linenums!`. This leads to cleaner output of the macros, e.g., on master one gets
```julia
julia> @macroexpand @scalar_rule identity(x) 1.0
quote                   
#= /home/david/.julia/packages/ChainRulesCore/JWrYo/src/rule_definition_tools.jl:94 =#
if !(identity isa ChainRulesCore.Type) && ChainRulesCore.fieldcount(ChainRulesCore.typeof(identity)) > 0
#= /home/david/.julia/packages/ChainRulesCore/JWrYo/src/rule_definition_tools.jl:95 =#
ChainRulesCore.throw(ChainRulesCore.ArgumentError("@scalar_rule cannot be used on closures/functors (such as $(identity))"))
end
#= /home/david/.julia/packages/ChainRulesCore/JWrYo/src/rule_definition_tools.jl:100 =#
begin
nothing
function …
```
> Use `Base.remove_linenums!` to obtain cleaner macro output

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
The PR interpolates ~~all types and functions that are not provided by the user~~ more types and functions in the AST in the macros `@scalar_rule` and `@non_differentiable`. This fixes the following bug:
```julia
julia> using ChainRulesCore: @non_differentiable
julia> @non_differentiable length(x::AbstractVector)
ERROR: UndefVarError: ChainRulesCore not defined
Stacktrace:
[1] top-level scope
@ ~/.julia/packages/ChainRulesCore/ASgvC/src/rule_definition_tools.jl:327
```
Additionally, not the whole output of `@non_differentiable` is escaped anymore, fixing a possible name collision for arguments of name `kwargs`:
```julia
julia> using ChainRulesCore: ChainRulesCore, @non_differentiable
julia> @non_differentiable length(kwargs::AbstractVector)
ERROR: syntax: function argument name not …
```
> Interpolate more in rule helpers and fix escaping of `@non_differentiable`

- Project.toml
- src/rule_definition_tools.jl
Contains the changes suggested in https://github.com/JuliaDiff/ChainRulesCore.jl/pull/325#issuecomment-811278617: Discarded arguments in the rules generated by `@non_differentiable` are marked with `@nospecialize`.
> Mark discarded arguments with `@nospecialize`

- Project.toml
- src/rule_definition_tools.jl
Fixes https://github.com/JuliaDiff/ChainRulesCore.jl/issues/328.
The underlying problem is https://github.com/JuliaLang/julia/issues/37134 which exists on Julia 1.5.0 and 1.5.1, and was fixed in Julia 1.5.2 (https://github.com/JuliaLang/julia/pull/37181).
I did not add any tests since the error is reproducible only with these Julia versions which currently are not tested on Github.
> Fix error of `@non_differentiable` on Julia 1.5.0 and 1.5.1 (#328)

- test/rule_definition_tools.jl
Add `sincos` example in https://github.com/JuliaDiff/ChainRulesCore.jl/issues/265 as regression test for type stability of scalar rules with multiple outputs, as suggested by @sethaxen in https://github.com/JuliaDiff/ChainRulesCore.jl/issues/265#issuecomment-810849858.
When I added the test, I noticed that probably the issue was fixed by https://github.com/JuliaDiff/ChainRulesCore.jl/pull/276 which already added some regression tests. I am not sure if it is worth adding the example from #265 as well.
> Additional regression test for type stability of scalar rules

- src/differentials/abstract_zero.jl
Currently, the admonition in the docstring of `DoesNotExist` is not correct and therefore not displayed properly (see https://juliadiff.org/ChainRulesCore.jl/dev/api.html#ChainRulesCore.DoesNotExist).
> Fix admonition

- Project.toml
- docs/src/api.md
- docs/src/writing_good_rules.md
- src/ChainRulesCore.jl
- src/differential_arithmetic.jl
- src/differentials/notimplemented.jl
- test/differentials/notimplemented.jl
- test/runtests.jl
This is a first draft that addresses https://github.com/JuliaDiff/ChainRulesCore.jl/issues/334. It adds an unexported `NotImplemented` differential that is constructed with an exported `@not_implemented` helper. If `ChainRulesCore.debug_mode() == true`, it tracks debugging information such as module and location where the differential is missing and, possibly, additional user-provided information. It throws an error if one tries to perform computations with the differential (I just implemented some of the methods that are defined for other differentials but maybe the list should be shortened or extended).
Examples:
```julia
julia> ChainRulesCore.debug_mode() = false # default
julia> zero(ChainRulesCore.@not_implemented())
ERROR: differential not implemented
Stacktrace:
...
julia> …
```
> Add `@not_implemented`

- Project.toml
- src/differential_arithmetic.jl
- src/differentials/composite.jl
- test/differentials/composite.jl
- test/differentials/notimplemented.jl
This PR fixes the test failures in https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/140.
~~Alternatively, one could~~ This PR allows `+(::NotImplemented, y)` (and permutations) more generally.
> Allow to sum `NotImplemented`

- Project.toml
- src/differentials/notimplemented.jl
- test/differentials/notimplemented.jl
With this PR the `@not_implemented` macro escapes the provided information.
I noticed that this would be useful when I updated SpecialFunctions in my fork (https://github.com/devmotion/SpecialFunctions.jl/tree/dw/notimplemented): now one can define a constant in the package and use it as message for multiple instances of `@not_implemented`.
> Escape information in `@not_implemented`

- Project.toml
- src/ChainRulesCore.jl
- src/precompile.jl
- src/ruleset_loading.jl
With this PR:
```
(ChainRulesCore) pkg> precompile
Precompiling project...
1 dependency successfully precompiled in 2 seconds (1 already precompiled)
julia> @time using ChainRulesCore
0.082255 seconds (157.13 k allocations: 9.737 MiB, 5.59% compilation time)
```
Before:
```
julia> @time using ChainRulesCore
0.111551 seconds (443.47 k allocations: 25.618 MiB, 3.87% compilation time)
```
Removing the hook alltogether:
```
julia> @time using ChainRulesCore
0.033357 seconds (36.37 k allocations: 2.399 MiB, 17.75% compilation time)
```
That's still more overhead than I'd like, so we should still discuss
whether we could avoid these hooks, but it does at least improve the current
situation somewhat.
Ref #340
> precompile package callback

- Project.toml
- src/accumulation.jl
- test/accumulation.jl
Its not as good as `add!!(::AbstractArray, ::InplacableThunk)` 
but if it can be inplace then it still saves 1 allocation (InplaceableThunk woulds save 2)/
> add!! with Thunk

- Project.toml
- src/deprecated.jl
- test/deprecated.jl
This deprecates `NO_FIELDS` to `NoTangent()`.
Note that this is not the same as the 0.9 behavour which had it as `ZeroTangent()`.
but it is close, and is the behavour we want going forward
(which is why we decided that this had to be in breaking change. But we ment to include it in the 0.10.0 release).
> deprecate NO_FIELDS

- docs/src/FAQ.md
Followup to https://github.com/JuliaDiff/ChainRules.jl/pull/425
> remove references to SpecialFunctions and NaNMath in the docs

- docs/src/writing_good_rules.md
This builds off @nickrobinson251's https://github.com/JuliaDiff/ChainRulesCore.jl/pull/331/files and adds an example struct, as well as adds a note on functors. I've also moved the Code Style to the top, as the generic signature is the most common thing people want.
Closes https://github.com/JuliaDiff/ChainRulesCore.jl/issues/315
> Improve docs for structs: constructors and functors

- Project.toml
- src/differentials/thunks.jl
- test/differentials/thunks.jl
Needed for defining `to_vec` for `@thunk`s, which is needed for [testing all kinds of differentials](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/159)
> Implement `Base.:(==)` for thunks

- src/deprecated.jl
- src/differentials/thunks.jl
- test/deprecated.jl
- test/differentials/thunks.jl
Always use `unthunk` instead.
Closes #374 .
> Deprecate calling thunks like functions

- .gitignore
- docs/Manifest.toml
- docs/make.jl
- docs/src/FAQ.md
- docs/src/complex.md
- docs/src/converting_zygoterules.md
- docs/src/design/many_differentials.md
Motivated by https://github.com/SciML/SciMLBase.jl/issues/69
(and the upcoming release of Diffractor which IAUI will require the use of ChainRulesCore rather than ZygoteRules)
[Docs preview](https://juliadiff.org/ChainRulesCore.jl/previews/PR378/converting_zygoterules.html)
> Write docs on converting ZygoteRules

- Project.toml
- src/differentials/thunks.jl
- test/differentials/thunks.jl
solving 1.0 errors in https://github.com/JuliaDiff/ChainRules.jl/pull/449
> Add more methods on thunks to make ChainRules work on 1.0

- src/differentials/composite.jl
- test/differentials/composite.jl
`Tangent{Foo}()` was printing as `Tangent{Foo}NamedTuple()"`
> Fix printing of Tangent{T} with empty backing

- Project.toml
- src/deprecated.jl
- src/differentials/thunks.jl
- test/accumulation.jl
- test/deprecated.jl
- test/differentials/thunks.jl
- test/runtests.jl
This closes #386 
I will wait til we merge the ProjectTo PR in ChainRules.jl before making the follow up there.
While doing this I noticed out deprecated tests were not running so i fixed that and fixed some issues with that file
> Change argument order on InplaceableThunk and fix deprecated tests

- Project.toml
- src/deprecated.jl
- src/differentials/composite.jl
- test/deprecated.jl
- test/differentials/composite.jl
> deprecate convert

- docs/src/index.md
Missing indent was splitting half the note "Why `rrule` returns a pullback ..."
outside the note box
> Fix indent of note in Introduction doc

- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
This is one commit from #391, which should possibly be removed there. 
Tests did pass with this in there. They will fail here, but aren't worth fixing until that is finalised & merged.
> Always include `ProjectTo` in `@scalar_rule`

- src/rule_definition_tools.jl
This broadcasting is causing a fair bit of trouble for nested AD in Diffractor, so I'd like to disable it. I believe the original purpose here was to enable chunked forwarddiff for ForwardDiff2, but since that is abandoned, I do not believe there are any current users. Diffractor will also need some sort of accommodation here for chunked forward mode, but it is unlikely to be broadcasting.
> Get rid of useless broadcasting

- docs/make.jl
- docs/src/api.md
- docs/src/opting_out_of_rules.md
- src/ChainRulesCore.jl
- src/rule_definition_tools.jl
- src/rules.jl
- test/rules.jl
closes #377 
This is actually very breaking so can't be merged til after we tag 1.0-DEV.
It will not break anything in practice til something uses it though.
and it won't break Diffactor.
It will break Zygote and Nabla.
Before mergjng this I want to make the corresponding changes to ChainRulesOverload generation,
and Zygote.
> Add opting out of rules

- Project.toml
- src/ChainRulesCore.jl
- src/projection.jl
In nested AD using `hasfield` makes Zygote sad.
Also it is ugly compared to `hasproperty`
I thought I caught all uses of this in #391
but one must have been missed -- it was a huge PR.
> use hasproperty, not hasfield for ProjectTo

- Project.toml
- src/projection.jl
- test/projection.jl
One option to fix  the issues with tying to use ForwardDiff on a `rrule` pullback that makes use of `ProjectTo`
See discussion on https://github.com/JuliaDiff/ForwardDiff.jl/pull/538.
Which fixes the following test that fails in https://github.com/FluxML/Zygote.jl/pull/1035/
```julia
using Zygote
dx, dy = diaghessian(f34, xs, y)
@test size(dx) == size(xs)
@test vec(dx) ≈ diag(hessian(x -> f34(x,y), xs))
@test dy ≈ hessian(y -> f34(xs,y), y)
```
This option basically says:
All subtypes of `Real` represent the same subspace: all of Real.
So if you give me one I am not familar with (e.g. `Dual`) I am just going to leave it alone.
But if you give a `AbstractFloat` subtype, I will fix the precision to match what i saw in the primal pass.
And if you give me an Integer I will make it a Float.
So …
> Don't try and convert to FloatX except if Integer or AbstractFloat (option 1)

- src/projection.jl
This should silence the following:
```
WARNING: local variable T conflicts with a static parameter in Type at /home/runner/work/ChainRulesCore.jl/ChainRulesCore.jl/src/projection.jl:368.
```
No functional change, no need for a release.
> Fix a warning in CI on 1.0

- Project.toml
- src/projection.jl
- src/rule_definition_tools.jl
By avoiding a lot of the kwarg machinery when it is not needed.
Helps get some Diffractor performance back after the ProjectTo
change.
Also fix an issue where `@scalar_rule` was using `typeof` not `Typeof`
creating incorrect rules for constructors.
> Reduce complexity of ProjectTo constructor

- Project.toml
- src/differentials/abstract_zero.jl
- src/projection.jl
- test/differentials/abstract_zero.jl
- test/projection.jl
There is a bit of a mismatch between ProjectTo (which is now fairly permissive) and Tangent & friends (which want to reconstruct precisely the same type of struct). This PR makes the former more often just pass the latter along. Thus:
```julia
julia> x = 1:3.0
1.0:1.0:3.0
julia> dx = Tangent{typeof(x)}(ref=NoTangent(),step=0.1,len=NoTangent(),offset=NoTangent());
julia> ProjectTo(x)(dx)
Tangent{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}(ref = NoTangent(), step = 0.1, len = NoTangent(), offset = NoTangent())
julia> y = 1.0+im;
julia> dy = Tangent{typeof(y)}(; re=NoTangent(), im=0.1);
julia> ProjectTo(y)(dy)
Tangent{ComplexF64}(re = NoTangent(), im = 0.1)
```
Here `dx` is supposed to be the gradient from say `last(x)/10`. That could have been …
> Fix #426 -- gradient of Ref is a Tangent

- .github/workflows/IntegrationTest.yml
StatsFuns 0.9.10 (released yesterday) uses CR 1. It has 655 dependents (93 direct ones) (https://juliahub.com/ui/Packages/StatsFuns/530lR/0.9.10?t=2) and therefore I think it could be useful to add it to the integration tests.
> Add StatsFuns to integration tests

- .github/workflows/IntegrationTest.yml
1.5 is old.
Some of our downstream doesn't support it as well.
E.g. ChainRules.jl only promises that things will pass the type inference checks on the latest release.
Which currently our reverse dep test fail because they are testing 1.5 where the ChainRules.jl tests fail at inference.
We could disable those inference tests, but we actually don't want to, since if a ChainRulesCore change breaks inference in ChainRules.jl then we want to know about it.
> Run integration tests on latest stable julia release

- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
This follows up on the discussion on Slack. It is a small refactor of `@scalar_rule` such that the actual derivative computation is factored out in an (internal) method
```julia
derivatives_given_output(Ω, f, xs...) # not sure about the signature, but this seemed reasonable
```
This allows some optimization if one happens to have both `xs` and `Ω` and does not want to recompute `f` to get derivatives. 
This does fix https://github.com/JuliaDiff/ChainRulesCore.jl/issues/246 in its original formulation (getting derivative without running primal pass for scalar rules). It is specific to scalar rules, it does not try to define a general API for `frule` and `rrule` when the output is known.
Notes:
- The second commit does a small `esc` fix, in that `_normalize_scalarrules_macro_input` was …
> Add `derivatives_given_output` for scalar functions

- Project.toml
- src/differentials/composite.jl
- test/differentials/composite.jl
also fixes some issues with `getindex`, mainly that it didn't
canonicalize tangents with NamedTuple backing, which I'd argue is a bug.
It's also more consistent with `getproperty` now, so `tangent[:a]`
returns `ZeroTangent()` instead of erroring if `tangent`'s backing
doesn't have a field `a`.
ref JuliaDiff/Diffractor.jl#39
> fix `getproperty(::Tangent, ::Int)` for NamedTuple

- Project.toml
- src/projection.jl
- test/projection.jl
Closes #442, I think. 
Besides `ProjectTo(::Any) = identity`, this also adds a few methods marking things like `Symbol, Char` as non-differentiable. Could also just leave them alone.
> Add `ProjectTo(::Any) = identity`

- docs/src/writing_good_rules.md
- clarify order of `@thunk` and `ProjectTo`
- correct misplaced paragraph
- document new behaviour of ChainRulesTestUtils#218
- improve example
- some minor typo edits
> Clarify "writing good rules" documentation

- Project.toml
- src/tangent_arithmetic.jl
- test/tangent_types/notimplemented.jl
This PR simplifies the arithmetic of `NotImplemented`. Mainly, it allows more operations that currently throw errors and it treats `NoTangent` like `ZeroTangent`. The basic rules in this PR are:
- `NotImplemented` always wins `+`
- `NotImplemented` loses `*` and `dot` against `NoTangent` and `ZeroTangent` (allows to ignore non-implemented partial derivatives) and wins `*` and `dot` against other types
- `+`, `*`, and `dot` definitions for `NotImplemented` and a value of a different type are commutative
The main motivation for this PR is to be able to test rules such as https://github.com/JuliaMath/SpecialFunctions.jl/pull/350#discussion_r720585597 more easily with something like
```julia
test_frule(besselix, nu, x) # derivative is `NotImplemented`
test_frule(besselix, nu ⊢ NoTangent(), x) …
```
> Simplify arithmetic of `NotImplemented` and treat `NoTangent` like `ZeroTangent`

- docs/src/index.md
Closes #314.
I chose a list with a description because there would be too much notes for Zygote.jl which makes the table ugly. Also, I couldn't quite figure how to add emojis and without their colour looking at "yes"s and "no"s is much less visually clear.
> Add rollout information

- Project.toml
- src/projection.jl
- test/projection.jl
This PR adds `ProjectTo(::NamedTuple)` according to the suggestion by @mcabbott (I added you as a co-author to give credit). I only added two additional more descriptive error messages and some tests, similar to the implementation for `Tuple`s.
Fixes https://github.com/JuliaDiff/ChainRulesCore.jl/issues/511.
> Add `ProjectTo(::NamedTuple)`

- src/tangent_types/abstract_zero.jl
- test/tangent_types/abstract_zero.jl
The constructor for `T<:Number` given a vararg number of
`AbstractZero` is ambiguous with any `Number` subtype
having a varargs constructor:
```julia
julia> module M
using ChainRulesCore
struct X{R} <: Number
a::R
hasvalue::Bool
function X{R}(a, hv=true) where {R}
isa(hv, Bool) || error("must be bool")
return new{R}(a, hv)
end
end
end
Main.M
julia> using Test
julia> detect_ambiguities(M)
5-element Vector{Tuple{Method, Method}}:
(Main.M.X{R}(a) where R in Main.M at REPL[1]:8, (::Type{T})(x::Base.TwicePrecision) where T<:Number in Base at twiceprecision.jl:255)
(Main.M.X{R}(a) where R in Main.M at REPL[1]:8, (::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} in Base at char.jl:50)
((::Type{T})(xs::ChainRulesCore.AbstractZero...) where T<:Number in ChainRulesCore at …
```
> Eliminate ambiguity with Number constructors

- src/tangent_types/thunks.jl
This calls `show(io, x)` within show methods, so that arrays get truncated to your screen.
> Don't use `repr` in `show`

- Project.toml
- src/projection.jl
- src/tangent_types/abstract_zero.jl
- test/projection.jl
This wants to make `I` be its own gradient, instead of using a Tangent. It's a vector space, and this simplifies some rules, as for instance `Tangent{UniformScaling{Int}}(λ=1) + [1 2; 3 4]` is an error.
Are there cases where this goes wrong? I guess that `I` is either constructed explicitly within code AD sees, or comes from outside; it is not going to be produced as the output of any rule's forward pass, and so won't travel backwards into any pullbacks which aren't expecting it (and hence may do things which fail, like `I .+ 1`). It certainly should not be produced as the gradient of say `tr`, it is not an acceptable cotangent for a matrix, only for another `I`.
> Projection for UniformScaling

- Project.toml
- src/projection.jl
- test/projection.jl
> implement projection for `InplaceableThunk`

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
- test/rules.jl
> Make `@opt_out rrule(...)` automatically qualify `rrule` namespace as `ChainRulesCore.rrule`

- .github/workflows/CI.yml
- Project.toml
I think we should no longer add new things here for Julia 1.0, when ChainRules is 1.6+. 
Xref #542 and https://github.com/JuliaDiff/ChainRules.jl/pull/571
> Drop Julia 1.0

- Project.toml
- src/tangent_types/thunks.jl
- test/tangent_types/thunks.jl
See https://github.com/JuliaDiff/ChainRulesCore.jl/issues/523 . Seems to only be used for tests according to the PR but it's a major compile time problem, so it doesn't make sense to keep them. This can be marked breaking if it breaks downstream, but it's rather easy to update downstream AD packages for this so the value proposition is pretty clear.
> Remove major invalidations from ==

- Project.toml
This PR adds support for Compat 4. In that release support for Julia < 1.6 was dropped and thereby dependencies could be reduced significantly. E.g., with Julia 1.8 beta3:
```julia
(jl_TxoY7w) pkg> add Compat@3
Updating registry at `~/.julia/registries/General.toml`
Resolving package versions...
Updating `/tmp/jl_TxoY7w/Project.toml`
⌃ [34da2185] + Compat v3.43.0
Updating `/tmp/jl_TxoY7w/Manifest.toml`
⌃ [34da2185] + Compat v3.43.0
[0dad84c5] + ArgTools v1.1.1
[56f22d72] + Artifacts
[2a0f44e3] + Base64
[ade2ca70] + Dates
[8bb1440f] + DelimitedFiles
[8ba89e20] + Distributed
[f43a241f] + Downloads v1.6.0
[7b1f6079] + FileWatching
[b77e0a4c] + InteractiveUtils
[b27032c2] + LibCURL v0.6.3
[76f85450] + LibGit2
[8f399da3] + Libdl
[37e2e46d] + LinearAlgebra
[56ddb016] + Logging
[d6f4376e] + …
```
> Support Compat@4

- Project.toml
- src/tangent_types/tangent.jl
- src/tangent_types/thunks.jl
- test/tangent_types/tangent.jl
- test/tangent_types/thunks.jl
> Shorten printing of `Tangent` and thunks

- docs/Manifest.toml
- docs/Project.toml
This PR makes https://github.com/JuliaDiff/ChainRulesCore.jl/pull/556 obsolete.
As detecting the devbranch has been added to Documenter itself.
A quick look at the docs suggest nothing has broken and that the edit link now goes to the right place (`main`)
> update to Documenter v0.27

- src/ChainRulesCore.jl
- src/accumulation.jl
- test/accumulation.jl
- test/tangent_types/tangent.jl
To be useful, this function should return true only when it is *certain* that the array can be written into. A false `false` costs one allocation, but a false `true` will lead to an error. At present, it guesses wrong for wrappers like ReadOnlyArrays.
Commit [c3bf4b0](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/577/commits/c3bf4b088a666c0e0b71da5b182d270ed4121d8b) is just fixing tests to pass on 1.9, could be pulled out.
> Take `is_inplaceable_destination` seriously

- Project.toml
- src/tangent_types/tangent.jl
I didn't check, but unbound type parameters often cause performance issues, so this isn't merely cosmetic.
FTR, there's a relevant function in Test in stdlib for checking this stuff:
https://docs.julialang.org/en/v1/stdlib/Test/#Test.detect_unbound_args
> remove unbound type parameters

- test/projection.jl
I think the policy is that we only care about performance/inference on the latest julia version.
> fix CI on 1.5

- Project.toml
- src/tangent_arithmetic.jl
- src/tangent_types/notimplemented.jl
- src/tangent_types/thunks.jl
- test/tangent_types/notimplemented.jl
- test/tangent_types/thunks.jl
Does not fix https://github.com/JuliaDiff/ChainRulesCore.jl/issues/588 but reduces method ambiguities from
```julia
julia> Test.detect_ambiguities(ChainRulesCore)
14-element Vector{Tuple{Method, Method}}:
(/(z::AbstractZero, ::Any) in ChainRulesCore at /home/david/.julia/packages/ChainRulesCore/Z4Jry/src/tangent_types/abstract_zero.jl:29, /(a, b::AbstractThunk) in ChainRulesCore at /home/david/.julia/packages/ChainRulesCore/Z4Jry/src/tangent_types/thunks.jl:37)
(/(a::AbstractThunk, b) in ChainRulesCore at /home/david/.julia/packages/ChainRulesCore/Z4Jry/src/tangent_types/thunks.jl:36, /(a, b::AbstractThunk) in ChainRulesCore at /home/david/.julia/packages/ChainRulesCore/Z4Jry/src/tangent_types/thunks.jl:37)
((::ChainRulesCore.var"#frule##kw")(kws, ::typeof(frule), ::RuleConfig, args...) …
```
> Fix some method ambiguities

- src/rule_definition_tools.jl
I found invalidations from loading both ChainRulesCore.jl and SciMLBase.jl using the beta of Julia 1.9:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("SciMLBase"); Pkg.develop("ChainRulesCore")
julia> using SnoopCompileCore; invalidations = @snoopr(using ChainRulesCore, SciMLBase); using SnoopCompile
julia> trees = invalidation_trees(invalidations)
[...]
inserting ==(retcode::SciMLBase.ReturnCode.T, s::Symbol) @ SciMLBase ~/.julia/packages/SciMLBase/QqtZA/src/retcodes.jl:348 invalidated:
backedges: 1: superseding ==(x, y) @ Base Base.jl:127 with MethodInstance for ==(::Any, ::Symbol) (12 children)
```
I fixed invalidations by using `===` instead of `==` when comparing to a `Symbol`, which is also recommended in the docstring of `Symbol`:
```julia
help?> Symbol
search: Symbol …
```
> use === instead of == to compare Symbols

- src/tangent_types/tangent.jl
- test/tangent_types/tangent.jl
closes #619 
This makes for a nice canonical way to decide if something should be pulled back.
Since even complicated structures like:
```julia
julia> iszero([0.0, NoTangent(), [ZeroTangent(), Tangent{Foo}()]])
true
```
work right.
So this is better than just checking top-level type.
It is much cheaper to check if something is zero, even if it involved elementwise work than the vast majority of pullbacks so i think a case can be made that this should always been done by the AD. Or at least the AD should have special cases for things to treat as as always nonzero like dense numerical mastrixes `<:Array{<:Real}` (which are also things that rules support).
This should go well with https://github.com/FluxML/Zygote.jl/pull/1389
> iszero for Tangents

- .github/workflows/CI.yml
This is forbidden by Project.toml: 
https://github.com/JuliaDiff/ChainRulesCore.jl/blob/ed9a0073ff83cb3b1f4619303e41f4dd5d8c4825/Project.toml#L16
Currently passes on CI, which must ignore that, e.g. https://github.com/JuliaDiff/ChainRulesCore.jl/actions/runs/4436617557/jobs/7785265494
> Stop testing on 1.5

- docs/src/design/changing_the_primal.md
The original link goes to the right page, but it doesn't take you to the linked section
> Change link to SemVer ref

- docs/src/FAQ.md
Add a section to the FAQ on the error
```julia
MethodError: no method matching iterate(::Nothing)
```
Partial fix for #632 until a breaking 2.0 release can get rid of the default dispatch
> Add explanation of `nothing` errors

- Project.toml
- src/tangent_types/abstract_zero.jl
- test/tangent_types/abstract_zero.jl
This is for the same reason `getindex` is defined.
Often you want to be able to treat a `ZeroTangent` as though it were a structural tangent.
So you want it to have the same fields as the primal just with them all zero
> Define getproperty on AbstractZeroTangents

- docs/src/maths/propagators.md
In response to a suggestion at [this](https://discourse.julialang.org/t/implementing-derivative-in-chainrules-for-function-with-internal-fields/66844/6?u=ablaom) Julia discourse thread.
Actually, there is an existing example in the docs, the "Pedagogical Example".  I expect it's still worth having another, simpler example, in the more specific context addressed here. At least, this would have helped me.
> Add illustration of `∂self` in the maths/propagators section

- src/tangent_types/abstract_zero.jl
- test/tangent_types/abstract_zero.jl
- test/tangent_types/tangent.jl
Fixes #639.
`norm` now returns 0 for the named tangents.
I noticed, however, that the similar implementations of `dot(tangent, tangent)` or `tangent*tangent` return `ZeroTangent()` instead. To my understanding, returning a tangent in those cases is never correct (probably `tangent*tangent` should not be defined at all). Probably that’s a different issue, but here it is the rationale for sticking with 0 for `norm`.
Please let me know if there is anything I can do to improve this!
> tangent_arithmetic: add `norm` for `NoTangent`, `ZeroTangent` and `NotImplemented`

- Project.toml
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
I am surprised we didn't run into this earlier.
I guess because noone has been using forward mode that seriously.
(in particular right now Diffractor doesn't support kwargs right: https://github.com/JuliaDiff/Diffractor.jl/issues/244)
Or maybe something changed in 1.10 (since https://github.com/JuliaDiff/ChainRules.jl/issues/765 also showed up)
Fixes https://github.com/SciML/Surrogates.jl/pull/462#issuecomment-1879935787
@ArnoStrouwen  can you confirm this fixes your problem, and if so approve this PR?
> Fix ambig with configured frule created by non_differentiable rule

- test/projection.jl
This is the companion to https://github.com/JuliaArrays/StaticArrays.jl/pull/1228
see that PR for full details.
the tl;dr is:
These tests were breaking because of a change made in StaticArrays to how projections work (good that's their job) away from the default behavour which is implemented in this package.
It thus no longer makes sense to test StaticArrays still has the default behavour in this package.
Since we can't influence that.
Possibly we should have some other type we use to test this?
Note: this is not quiet enough to drop StaticArrays as a dependency entirely, as it is still used to test inplace accumulation into an immuatable array.
> Delete StaticArrays Projection tests

- docs/src/rule_author/superpowers/ruleconfig.md
As we are on the verge of landing actual (experimental) mutation support with #626 
it would be confusing to have docs using this as an example of something we might want to use a config for in the future.
> Remove example of mutation support config from docs

- src/tangent_types/structural_tangent.jl
Closes #658 
having a `UInt64` where I meant `UInt` broke dispatch and made it ignore the overload for the `hash` function
> Fix hash(::MutableTangent) on 32 bit

- Project.toml
- src/rule_definition_tools.jl
Fixes all the method ambiguities reported in ChainRules CI for julia 1.10
```julia
julia> filter(Test.detect_ambiguities(ChainRules, ChainRulesCore)) do t
(t[1].name in [:rrule, Symbol("rrule##kw")])
end
Tuple{Method, Method}[]
```
closes https://github.com/JuliaDiff/ChainRules.jl/issues/777
> Restrict kwarg type in code generated by @non_differentiable macro

- src/tangent_types/abstract_zero.jl
- src/tangent_types/structural_tangent.jl
- test/tangent_types/abstract_zero.jl
I do vaguely wonder if we should just preemptively walk things and if we don't find an AbstractFloat element always return `NoTangent`.
But for now I am just marking a bunch of stuff that has no tangent space as  `zero_tangent(x)=NoTangent()`
Also fixes `AbstractDict` though we have never properly implemented dict support in AD.
> Define a bunch of zero_tangents that should just NoTangent

- src/tangent_types/abstract_tangent.jl
- test/tangent_types/structural_tangent.jl
Basically #660 
though I implemented it on AbstractTangent.
Subtraction should be implemented the same.
We already have special cases for this on AbstructThunks, ZeroTangent and NotImplemented.
Potentially the AbstractThunk one could be removed. I don't think the ZeroTangent one could since strong zero
> add scaling division

- src/tangent_types/abstract_zero.jl
The pairs one shows up for keyword arguments.
> handling type-known empty containers in zero_tangent

- src/tangent_types/abstract_zero.jl
- test/tangent_types/abstract_zero.jl
Doing this improves type stability of Diffractor's forwards mode since if you have code that is like
```julia
y_smallest = if x>y
y<z
else 
false
end
```
then the first branch would get a tangent of `NoTangent()` due to the fact that we have `@non_differentiable Base.:>(::Any, ::Any)`.
But the second would (without this PR)  get a tangent of `false`.
I am tempted to make this Integers.
But seemed starting conservative with Bool might be better
@willtebbutt  you have thought about this a lot, what do you think?
> Bools have no tangent

- docs/src/index.md
This is still perhaps not great but it is an improvement
> Update supporting AD engines

- docs/src/index.md
closes #675 
cc @tansongchen cc @wsmoses
Feel free to use the suggest changes if you want to add any words
> Add more engines supporting ChainRules to the docs

- Project.toml
- src/ChainRulesCore.jl
- src/rule_definition_tools.jl
- test/rule_definition_tools.jl
> make `@non_differentiable` use identical pullbacks when possible

- Project.toml
- src/tangent_types/abstract_zero.jl
- test/tangent_types/abstract_zero.jl
In support of: https://github.com/JuliaDiff/ChainRules.jl/pull/808
> Add type promotion rules for `NoTangent` and `ZeroTangent`, and add `eltype` for `NoTangent`

- Project.toml
- src/tangent_types/thunks.jl
Needed for lazy Zygote:
https://github.com/FluxML/Zygote.jl/pull/966
Also bumped patch version so that we can tag a release afterwards.
> Disable thunks for 2nd order AD
